### ISSUE TITLE
Translations with weblate

### ISSUE THREAD

**Issue by 01micko** [labwc/labwc-tweaks-gtk#17]
I opened an account at https://hosted.weblate.org  for `labwc-tweaks-gtk`

Below you can see it:

https://hosted.weblate.org/projects/labwc-tweaks-gtk/

If you want to translate this project go to:  https://hosted.weblate.org/engage/labwc-tweaks-gtk/ and register.

To do:

- [x] add this info to README.md when @WeblateOrg aproves my account for a free account, which depends on the licence, no issue there
- [x] add the badge for translations
- [x] add message about using PR method for those who don't want to use weblate
- [x] add instructions for code contributors 
- [x] ~add a note to translate `data/labwc-tweaks-gtk.desktop`~ no longer needed, added in #20

The badge:

![status badge](https://hosted.weblate.org/widget/labwc-tweaks-gtk/multi-green.svg)

@johanmalm @stefonarch

**Comment by comradekingu** [comment]
I think mention in the README is a prerequisite for approval.

**Comment by 01micko** [comment]
Thanks, then I should merge this?
