### ISSUE TITLE
enhancement: remove call to 'killall' in update.c

### ISSUE THREAD

**Issue by 01micko** [labwc/labwc-tweaks-gtk#7]
This utility  was written before `labwc -r` was even a thing. I can't see a problem if we are calling an external `killall` then why not keep it in the family, so to speak, and call `labwc -r`. :smile:

**Comment by johanmalm** [comment]
Have done the same with the qt version

**Comment by 01micko** [comment]
Yes, good idea because old stray binaries might be lying around.
