### ISSUE TITLE
Please add this to AUR

### ISSUE THREAD

**Issue by letkan** [labwc/labwc-tweaks-gtk#9]
It would be nice to add labwc-tweaks-gtk to Arch Linux AUR and rename the QT version accordingly.

**Comment by Consolatis** [comment]
CC @redtide as maintainer of the labwc-tweaks-git package.

**Comment by johanmalm** [comment]
redtide has been inactive for some time.
I think the only option is to contact the maintainers at Arch, or find someone who is willing to take up maintainership.
I think it's better if upstream devs (us) do not also maintain our own packages. The separation is healthy.
